from .bd_cspn import BDCSPN
from .feat import FEAT
from .few_shot_classifier import FewShotClassifier
from .finetune import Finetune
from .laplacian_shot import LaplacianShot
from .matching_networks import MatchingNetworks
from .prototypical_networks import PrototypicalNetworks
from .pt_map import PTMAP
from .relation_networks import RelationNetworks
from .simple_shot import SimpleShot
from .tim import TIM
from .transductive_finetuning import TransductiveFinetuning
from .clip_texte_prototypical_networks import TextPrototypicalNetworks
from .S2P import S2P
from .FreqFusion import FreqFusion